<?xml version="1.0" encoding="UTF-8"?>
<!-- Parte del DTD-->
<!DOCTYPE marcadores [
    <!ELEMENT marcadores (pagina)*>
    <!ELEMENT pagina (nombre, descripcion, url)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT url (#PCDATA)>
]>
<!-- Parte de XML-->
<marcadores>
    <pagina>
        <nombre>Abrirllave</nombre>
        <descripcion>Tutoriales de informatica</descripcion>
        <url>https://www.abrirllave.com</url>
    </pagina>
    <pagina>
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre.</descripcion>
        <url>https://www.wikipedia.org</url>
    </pagina>
    <pagina>
        <nombre>W3C</nombre>
        <descripcion>World Wide Web Consortium.</descripcion>
        <url>https://www.w3.org</url>
    </pagina>

</marcadores>