<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia [
    <!ELEMENT geografia (paises,cuidades)>
    <!ELEMENT paises (pais)*>
    <!ELEMENT pais (#PCDATA)>
    <!ATTLIST pais codpais ID #REQUIRED>
    <!ELEMENT ciudades (ciudad)*>
    <!ELEMENT ciudad (#PCDATA)>
    <!ATTLIST ciudad pais IDREF #IMPLIED>
]>
<geografia>
    <paises>
        <pais codpais="uno">Argentina</pais>
        <pais codpais="dos">Argentina</pais>
        <pais codpais="tres">Argentina</pais>
        <pais codpais="cuatro">Argentina</pais>
    </paises>
    <ciudades>
        <ciudad pais="espaÃ±a">hola</ciudad>
    </ciudades>

</geografia>