<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE lista_de_personas [
    <!ELEMENT lista_de_personas (persona*)>
    <!ELEMENT persona (nombre,fechanacimiento,(telefono)+,sexo?,numeroseguridadsocial?)>
    <!ATTLIST persona nacionalidad CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA) >
    <!ELEMENT fechanacimiento (#PCDATA) >
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT sexo (#PCDATA) >
    <!ELEMENT numeroseguridadsocial (#PCDATA)>
]>

<lista_de_personas>
    <persona nacionalidad="español">
        <nombre>Ángel García</nombre>
        <fechanacimiento>25/04/1984</fechanacimiento>
        <telefono>670245656</telefono>
        <telefono>968456898</telefono>
        <sexo>Varón</sexo>
    </persona>
    <persona nacionalidad="español">
        <nombre>Juan Sinnombre</nombre>
        <fechanacimiento>25/04/1988</fechanacimiento>
        <telefono>670456256</telefono>
        <numeroseguridadsocial>256945666569</numeroseguridadsocial>
    </persona>
</lista_de_personas>