=== Snakeyesmp/LenguajeDeMarcas-1DAM/3ºEvaluacion/XML/03- Ejercicios 04-05-2023/03-Lungo.dtd
<!ELEMENT empresa (pedidos+)>
<!ELEMENT pedidos (sucursal+)>
<!ELEMENT sucursal (direccion+,trabajador,fecha,observacion?,articulo+)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observacion (#PCDATA)>
<!ELEMENT articulo (unidades,precio,observaciones?,plazo)>
<!ATTLIST articulo codigo CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== Snakeyesmp/LenguajeDeMarcas-1DAM/3ºEvaluacion/XML/03- Ejercicios 04-05-2023/03-SucursalLuengo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "03-Lungo.dtd">

<empresa>
    <pedidos>
        <sucursal codigo="Cod1">
            <direccion> </direccion>
            <trabajador> </trabajador>
            <fecha> </fecha>
            <observacion> </observacion>
            <articulo codigo="Cod2">
                <unidades> </unidades>
                <precio> </precio>
                <observaciones> </observaciones>
                <plazo> </plazo>
            </articulo>
        </sucursal>
    </pedidos>
</empresa>
